// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Metadatum struct {
	UserID    int32
	Name      string
	Surname   string
	Class     string
	Room      string
	UpdatedAt time.Time
}

type Role struct {
	ID              int32
	Alias           string
	IsDefault       bool
	IsSuper         bool
	PermissionsMask int64
}

type User struct {
	ID           int32
	Login        string
	RoleID       int32
	PasswordHash string
	CreatedAt    time.Time
}
